### ISSUE TITLE
Calculation of relative abundance

### ISSUE THREAD

**Issue by ssun6** [wwood/CoverM#10]
Hello, 

I was wondering how the relative abundance is calculated. I saw in your test code the results below:
"                "Sample	Genome	Relative Abundance (%)	Mean
7seqs.reads_for_seq1_and_seq2	unmapped	0	NA
7seqs.reads_for_seq1_and_seq2	genome1	0	0
7seqs.reads_for_seq1_and_seq2	genome2	53.16792	1.4117647
7seqs.reads_for_seq1_and_seq2	genome3	0	0
7seqs.reads_for_seq1_and_seq2	genome4	0	0
7seqs.reads_for_seq1_and_seq2	genome5	46.832077	1.2435294
7seqs.reads_for_seq1_and_seq2	genome6	0	0"

It looks to me that the 53% is just 1.41/(1.41+1.24). But in the wiki, the calculation considers the percentage of total reads that were mapped. Could you provide a more detailed explanation of the calculation? Thank you very much!

**Comment by wwood** [comment]
Indeed, but then that also equals 1.41/(1.41+1.24) * 24/24.

All reads map. Let me know if that is still insufficient an explanation.
Thanks for you interest. ben

**Comment by ssun6** [comment]
Thank you very much for your quick reply! My understanding is that: for example, there are m reads in a sample and n genomes in the reference. The mean of one read for one genome is M. The mean of genome j for the whole sample will be ![image](https://user-images.githubusercontent.com/49845798/60901431-f1805380-a23b-11e9-9f1b-d9a61cb275ab.png)
and the relative abundance will be 
![image](https://user-images.githubusercontent.com/49845798/60903118-c1867f80-a23e-11e9-8d49-20dd2cc8dbd0.png). Is this correct? 

Thank you very much for your time!
Shan

**Comment by wwood** [comment]
Hmm, not quite. First a mean of each genome is calculated, to get the ratios between each genome. Then all those ratios are scaled by the total number of mapped reads.
There is also some small extras like exclusion of the end of contigs and removal of low coverage genomes.

**Comment by ssun6** [comment]
Is the mean of each genome the sum of all the contigs? I ran some of my samples with coverM and the ratio of mean and relative abundance is always around 2000. Does this mean there are 2000 mapped reads? Thanks!

**Comment by wwood** [comment]
The mean of each genome is the mean across the contigs, not the sum. Each base gets equal weighting, except the 75bp on each end of the contig, which are ignored.

Mean and relative abundance have different units. Mean is the average number of reads overlapping each base pair (so a float >= 0). Relative abundance attempts to estimate the fraction of cells in a microbial community which belong to the lineage of each genome. So for instance in isolate systems, where there is only one community member, the relative abundance of that community member will be 100% (assuming all reads pass the mapping thresholds), while the mean can be anything >= 0 depending on sequencing depth.

**Comment by ssun6** [comment]
Got it, thank you very much for your help!
