### ISSUE TITLE
the sum of relative abundances less than 100

### ISSUE THREAD

**Issue by WJunHao** [wwood/CoverM#103]
Good day! I am confused about the sum of relative abundance. Why is the sum of relative abundances less than 100? I have six groups, and the relative abundance of all MAGs in each group adds up to less than 100.  Is this phenomenon normal and how can this result be explained? Thank you! My code was `coverm genome --coupled ../Raw_data/ND_A_R1.fq ../Raw_data/ND_A_R2.fq ../Raw_data/ND_B_R1.fq ../Raw_data/ND_B_R1.fq ../Raw_data/ND_C_R1.fq ../Rawdata/ND_C_R2.fq --genome-fasta-directory MAGs_fna/ -t 8 --bam-file-cache-directory ./bam_file_cache_directory --min-covered-fraction 0.0001 --discard-unmapped`

**Comment by wwood** [comment]
Hi,

It is because some reads are unmapped. The fraction of reads that are unmapped is the fraction of reads that are missing from the 100%.

Hope that helps.
