### ISSUE TITLE
Abundance calculation about genome

### ISSUE THREAD

**Issue by maocheng2020** [wwood/CoverM#105]
Hi，When I run with the following command,
coverm genome --coupled A_**R1**.fastq A_**R2**.fastq B_R1.fastq B_R2.fastq C_R1.fastq C_R2.fastq D_R1.fastq D_R2.fastq E_R1.fastq E_R2.fastq F_R1.fastq F_R2.fastq \
--genome-fasta-directory bin \
-o output.tsv \
--min-read-percent-identity 0.95 --min-read-aligned-percent 0.75 --trim-min 0.10 --trim-max 0.90 --threads 6

I got,
In sample 'A_**R1**.fastq', found 6036415 reads mapped out of 138369022 total (4.36%),
In sample 'B_**R1**.fastq', found 6368243 reads mapped out of 142599600 total (4.47%)......

and the output.tsv ,I found no information about ***R2**.fastq',I expected the result to be the abundance of the sample A instead of sample A_R1.fastq.
Sorry to bother you，thanks.

**Comment by rhysnewell** [comment]
Hi!
This is standard behaviour, CoverM just uses the forward read filename as a proxy for the sample name as whole. It's definitely mapping both forward and reverse reads.

Cheers,
Rhys

**Comment by Sabrin2020** [comment]
I tried ti update doesnot work. I uninstalled and reinstalled from here https://anaconda.org/bioconda/coverm but ended up with same version. How can I install latest version with conda please?
