### ISSUE TITLE
does not contain split symbol

### ISSUE THREAD

**Issue by TKsh6** [wwood/CoverM#116]
When I was running this command:
`coverm genome -m relative_abundance -b ./coverm_filter_res/${each_id}.filter.bam -s c -o ./abundance/${each_id} --threads 18`
I encontered this problem:
```
[2022-05-19T04:29:06Z INFO  coverm] CoverM version 0.6.1
[2022-05-19T04:29:06Z INFO  coverm] Writing output to file: ./abundance/ERR5766183
[2022-05-19T04:29:06Z INFO  coverm] Using min-covered-fraction 10%
thread 'main' panicked at 'Contig name k141_36901 does not contain split symbol, so cannot determine which genome it belongs to: "Element not found in slice"', src/genome.rs:813:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
How can I do to deal with this?

Yours S

**Comment by wwood** [comment]
Hi,

`-s` defines a character in a contig name that separates the genome name from the contig name. For instance in

```
>genome1=contig43
```

You would use `-s =`. You've specified `-s c` but c is not a character in `k141_36901` so CoverM croaks.

HTH, ben

**Comment by TKsh6** [comment]
Thank you for your response!
Besides, the contig name is just like this, so what kind of `-s` should I use?
```
>k141_6380
TATTTGGCTTATATCTAGATGCCTGCATCCAGTTAAAGTATGGTCCCTTAATAACATCTC
CAAACTATATTGCTGGAAAGAGTCTAAGAAAGAAATATGATCCTGCTTTTATTGAAAAAA
TAAAGGATATGGAAAACAAAGCGTAACAAAAATATTGTTGTTGTAGAAAAAGTATGCT
```

**Comment by TKsh6** [comment]
Thanks, I have done it.
