### ISSUE TITLE
coverm cluster to dereplicate --Parsing error in CheckM tab table file

### ISSUE THREAD

**Issue by uqmwu** [wwood/CoverM#118]
Hi Wood,

I try to use the coverm cluster function to dereplicate the genomes,
Here is the command I used,
coverm cluster -x fa --genome-fasta-directory /scratch/project/alkane/Mengxiong/C3_anammox/C3_anammox_BINNING/maxbin2_bins --checkm-tab-table /scratch/project/alkane/Mengxiong/C3_anammox/C3_anammox_BINNING/maxbin2_checkm_output/storage/checkm_maxbin2.tsv --min-completeness 70 --max-contamination 10 --output-representative-fasta-directory /scratch/project/alkane/Mengxiong/C3_anammox/C3_anammox_BINNING/drep_out

But I get the error: ERROR checkm] Parsing error in CheckM tab table file - didn't find 13 columns in line StringRecord.

Can you help check what is the issue here? Thank you!

**Comment by wwood** [comment]
Hi there,

Looks like there is some problem with your input file. It should be the output of when you run `checkm lineage_wf --tab_table` (I think that's the command, from memory)

ben

**Comment by uqmwu** [comment]
Thanks ben,
I have updated the checkm tab table, but got another error,
[2022-06-03T02:27:20Z INFO  bird_tool_utils::clap_utils] coverm version 0.3.0
[2022-06-03T02:27:20Z INFO  bird_tool_utils::external_command_checker] Found fastANI version 1.32
[2022-06-03T02:27:20Z INFO  galah::cluster_argument_parsing] Reading CheckM tab table ..
[2022-06-03T02:27:20Z INFO  galah::cluster_argument_parsing] Calculating num_contigs etc. for genome quality assessment ..
[2022-06-03T02:27:21Z INFO  galah::cluster_argument_parsing] Read in genome qualities for 74 genomes. 29 passed quality thresholds
thread 'main' panicked at 'Unable to parse version for dashing (error 1)', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bird_tool_utils-0.3.0/src/external_command_checker.rs:99:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
What is the issue here? Thanks!

**Comment by wwood** [comment]
HI,

That is an entirely unrelated issue, and is due to the way dashing was installed. When installed through conda, it sometimes doesn't work because it is compiled for the wrong CPU architecture. See https://github.com/wwood/CoverM/issues/45

I think I've answered the issue raised here so closing, but feel free to open another ticket if you have further problems.
THanks, ben
