### ISSUE TITLE
relative-abundance

### ISSUE THREAD

**Issue by daisyzhangsysu** [wwood/CoverM#13]
Dear developer:
I successfully use CoverM to calculate the coverages of my genome coming from metagenomic data. And i use trimmed_mean method. But i got a question with my coverage data. There are so many MAGs in my sample, so i would not like plot all of the MAGs' abundance in a figure. And i want to classify all the MAGs in the level of phylum. I mean, can i add the Trimmed_mean coverage value of MAGs in the same phylum together and use the finally combined value to respresent the abundance of this phylum?

**Comment by wwood** [comment]
Hi,

Using trimmed_mean to work out relative abundance, and then grouping the genomes by phyla seems reasonable to me, except that you'll have to account for the unmapped reads - you could do this by using `-m trimmed_mean relative_abundance` and then using the unmapped fraction from the relative_abundance, perhaps.
