### ISSUE TITLE
how to change the temporary directory 

### ISSUE THREAD

**Issue by lonestarling** [wwood/CoverM#140]
Hi

I always meet the error "thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: StorageFull, error: PathError { path: "/tmp/.tmpoLeFBK", err: Os { code: 28, kind: StorageFull, messa>
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace"
i think the key is how to change the temporary dierctiory manually rather the default /tmp dierctory. So how could i change?
Thanks!
L

**Comment by wwood** [comment]
Yes, see
https://wwood.github.io/CoverM/coverm-genome.html#frequently-asked-questions-faq

Ok?
-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT

________________________________
From: lonestarling ***@***.***>
Sent: Friday, 4 November 2022, 10:38 am
To: wwood/CoverM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wwood/CoverM] how to change the temporary directory  (Issue #140)


Hi

I always meet the error "thread 'main' panicked at 'called Result::unwrap() on an Err value: Custom { kind: StorageFull, error: PathError { path: "/tmp/.tmpoLeFBK", err: Os { code: 28, kind: StorageFull, messa>
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace"
i think the key is how to change the temporary dierctiory manually rather the default /tmp dierctory. So how could i change?
Thanks!
L

―

**Comment by lonestarling** [comment]
Hi
Absolutely, I have read the FAQ but i can't understand clearly, i have tried  that changed the  environment variable in my .bashrc file like this "export TMPDIR=$PATH:/home/covermtmp", but it looks like did't work out,   so can you describle it in detail?
appreciate it
L

**Comment by lonestarling** [comment]
Thank you professor， it helps a lot

**Comment by wwood** [comment]
No problem. OK, I guess you sorted this. Let me know if not.
