### ISSUE TITLE
Extracting bam files

### ISSUE THREAD

**Issue by ntromas** [wwood/CoverM#166]
Hi!

I wonder if the extracted bam files with the following parameter: --bam-file-cache-directory & --discard-unmapped includes the mapped reads from both R1 and R2 (I guess yes but the filename is only using R1 filename) and if the bam file is sorted (to extract mapped reads later for example).

Cheers!

Nico

**Comment by wwood** [comment]
Hi,

Sorry for the late response here.

Yes is the answer.

HTH,
ben
