### ISSUE TITLE
How can I provide extra parameters to BWA using the "--bwa-params" option?

### ISSUE THREAD

**Issue by ilnamkang** [wwood/CoverM#168]
Hi,

I'd like to give extra parameters to BWA, but I can't know how to do it correctly.

Take the "-a" option as an example.

I tried the arguments below, but nothing worked. How can I give extra parameters to BWA?

--bwa-params -a
--bwa-params '-a'
--bwa-params "-a"
--bwa-params a
--bwa-params 'a'
--bwa-params "a"

Also, error messages likely say that I have to use "--bwa-parameters",  not "--bwa-params". What is the correct option to give extra parameters?

Thanks.

**Comment by wwood** [comment]
Hi,

Sorry I guess the documentation must be incorrect. I'm afk ATM so can't check properly, but maybe try 

--bwa-parameters "'-a'"

You could also turn on debug so you know the right call is being made.

**Comment by ilnamkang** [comment]
Thank you for your quick reply.

I've tested further.

The correct name of the option is "--bwa-parameters", not "--bwa-params".

This option seems to be available in "coverm make", but not in "coverm genome".
I was confused because this option is listed on the usage page of "coverm genome". (https://wwood.github.io/CoverM/coverm-genome.html)

For "coverm make", "--bwa-parameters -a" seems to work.

Thanks.

**Comment by wwood** [comment]
Thanks for this @ilnamkang - it is fixed for the next version i.e. make accepts --bwa-params and --bwa-parameters, either is fine. Closing now.
