### ISSUE TITLE
libtinfow.so.6: no version information available (required by samtools)

### ISSUE THREAD

**Issue by bhimbbiswa** [wwood/CoverM#170]
Hi,

Already been solved, adding here for information to others.

I faced the above problem when I installed coverm to my institute cluster using the following command.

```
conda create -n conda coverm
```

I thought the problem is with ncurses following this advice,
https://stackoverflow.com/questions/72103046/libtinfo-so-6-no-version-information-available-message-using-conda-environment 
so installed it separately in a new environment and then installed coverm.
```
conda create -n conda coverm2 -c conda-forge ncurses
conda activate coverm2
conda install coverm
```
This also doesn't solve the problem.

Later I found Samtools has an issue about this problem.

https://github.com/samtools/samtools/issues/1822

So, I followed the advice of @jmarshall and set the priority channel using the following command.
```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda config --set channel_priority strict
```
This solved the problem for me.

**Comment by wwood** [comment]
Ah, thanks. Ouch. A transient problem which will hopefully be fixed soon by bioconda.

Since you did a great job outlining the problem and solution, I'm closing this. Thanks.

**Comment by ywbzhang** [comment]
I cannot solve this problem based on the above method. However, I used "conda install -y samtools=1.6 htslib=1.6" to demote samtools and htslib, and the problem was solved perfectly.

**Comment by ywbzhang** [comment]
> I cannot solve this problem based on the above method. However, I used "conda install -y samtools=1.6 htslib=1.6" to demote samtools and htslib, and the problem was solved perfectly. It is worth noting that this installation process is very long and requires patience.
