### ISSUE TITLE
default rep seq picking method

### ISSUE THREAD

**Issue by itsmisterbrown** [wwood/CoverM#173]
hi,

thanks for making such a great tool with myriad excellent functions. Sorry if I missed this somewhere, but how does coverm choose a representative sequence during clustering and is there a way to modify this?

thanks!

**Comment by wwood** [comment]
Hi,

Thans for the kinds words.

CoverM uses the galah code underneath https://github.com/wwood/galah - you can see an explanation on the README there. Perhaps easiest way to modify using an aribtrary ranking metric is to provide the genomes without checkm stats but in an order that respects the order of your preference for it being a rep. Alternatively several ranking metrics are provided in galah / coverm.

HTH, ben

**Comment by itsmisterbrown** [comment]
thanks for the speedy response, Ben. Sorry that my closing of this issue wasn't as fast. doing it now!
