### ISSUE TITLE
How to cite CoverM

### ISSUE THREAD

**Issue by SarahIsme** [wwood/CoverM#176]
I cannot find the paper describing CoverM, and the parameter "--full-help" do not provide the citation information.

So, could you please tell me how to cite CoverM, for example, the github page?

Thanks!

**Comment by rrohwer** [comment]
I did this:
Woodcroft, B. CoverM: Read coverage calculator for metagenomics. https://github.com/wwood/CoverM.

??

**Comment by AroneyS** [comment]
We have now added a CITATION.cff with a Zenodo doi (also see https://zenodo.org/records/10531254).
