### ISSUE TITLE
An error during the installation of development version

### ISSUE THREAD

**Issue by ilnamkang** [wwood/CoverM#181]
I'm trying to install the development version.

I encountered an error when I ran "cargo run -- genome ...etc...".

The error message is below.

Would you let me know the cause of this error and how I can avoid the error?

Thanks.

\------
...
...
...
   Compiling rust-htslib v0.44.1
   Compiling skani v0.1.1
   Compiling galah v0.3.1 (https://github.com/wwood/galah#113035e8)
   Compiling coverm v0.6.1 (/home/kangin/Programs/CoverM)
error[E0063]: missing field `dereplication_cluster_method_argument` in initializer of `GalahClustererCommandDefinition`
  --> src/cli.rs:27:9
   |
27 |         galah::cluster_argument_parsing::GalahClustererCommandDefinition {
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `dereplication_cluster_method_argument`

For more information about this error, try `rustc --explain E0063`.
error: could not compile `coverm` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
\------

**Comment by wwood** [comment]
Hi, 

Is this fixed in the commit I jus pushed, 66bff34 ?

**Comment by ilnamkang** [comment]
Hi,

I'm not sure if this problem has been fixed or not. I encountered a warning message (see below).

But anyway, after building, I can run ~/CoverM/target/debug/coverm without errors.

\------
   Compiling skani v0.1.1
   Compiling galah v0.3.1 (https://github.com/wwood/galah#113035e8)
   Compiling coverm v0.6.1 (/home/kangin/Programs/CoverM)
    Finished dev [unoptimized + debuginfo] target(s) in 35.88s
warning: the following packages contain code that will be rejected by a future version of Rust: buf_redux v0.8.4, partitions v0.2.4
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
     Running `target/debug/coverm genome ...etc...`
error: unexpected argument '...etc...' found

Usage: coverm genome [OPTIONS]

For more information, try '--help'.
\------

**Comment by wwood** [comment]
Hi,

It appears you might be specifying the command line incorrectly?


If the problem persists let me know what you used.
Thanks

**Comment by ilnamkang** [comment]
Hi,

1\) The error was due to my mistake in the command. My command included "...etc...".

$ cargo run -- genome **...etc...**

2\) The warning below seems to persist when I run  "cargo run -- genome". But, I can run the built coverm without any problems.

warning: the following packages contain code that will be rejected by a future version of Rust: buf_redux v0.8.4, partitions v0.2.4
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
