### ISSUE TITLE
Support for strobealign

### ISSUE THREAD

**Issue by PoisonAlien** [wwood/CoverM#186]
Hi,

Thanks for the tool. Could you please consider supporing [strobealign](https://github.com/ksahlin/strobealign) as a mapper option. It has both the aligner and mapping functions - similar to minimap2 - and can output PAF as well. 
I guess this would make integration bit easier?

**Comment by julianzaugg** [comment]
@wwood just adding to this. As per the changelog, it appears as strobealign support was added in ver. `0.7.0`, however it is not listed under `--mappers` in the documentation (at least for `coverm genome`; other related parameters are present, e.g. `--strobealign-params`). I also just installed ver. `0.7.0` through conda and it appears to have failed to install strobealign.
