### ISSUE TITLE
What is the formula for function "Mean"

### ISSUE THREAD

**Issue by Harper19** [wwood/CoverM#191]
Appreciate the development of this great tool. For the function Mean, I am a little bit confused about the formula. 
I would assume it is mainly based on total mapped bases/genome length. Is it correct? Or the denominator would be the covered bases only and the not covered region will not be take into calculation?

Thanks!
Harper

**Comment by wwood** [comment]
Thanks for kind words.

It's the whole genome size, assuming you are working in genome mode.

There's an example in the readme which might help too.
