### ISSUE TITLE
coverm seems only used the forward reads

### ISSUE THREAD

**Issue by quliping** [wwood/CoverM#194]
CoverM is useful to caculate the abundance of genomes. However, I am confused about the output of coverm. Here are to command line that I have tried before (one with '-1' and '-2', one with '--coupled'):

```
1.  
coverm genome --coupled ${workdir}/01_READ_QC/${line}_1.fastq ${workdir}/01_READ_QC/${line}_2.fastq -x fa -d ${genome_dir} -p minimap2-sr -m relative_abundance -o ${outdir}/${line}.comverm-out.txt --output-format dense -t $threads --bam-file-cache-directory ${outdir}/temp_dir
2. 
coverm genome -1 ${workdir}/01_READ_QC/${line}_1.fastq -2 ${workdir}/01_READ_QC/${line}_2.fastq -x fa -d ${genome_dir} -p minimap2-sr -m relative_abundance -o ${outdir}/${line}.comverm-out.txt --output-format dense -t $threads --bam-file-cache-directory ${outdir}/temp_dir
```

However, coverm seems only used the forward reads of the two paired reads? Is this just a descriptive textual error or the software really only used the forward sequences?

![image](https://github.com/wwood/CoverM/assets/39583607/b64f8abb-4f2b-44b4-862e-00b81e478d55)
![image](https://github.com/wwood/CoverM/assets/39583607/94a11971-2a18-45e7-b609-6a4d35dc63a0)

**Comment by rhysnewell** [comment]
Sample names in the coverage file are generated using the forward reads when using -1 and -2 parameters, both pairs are used during mapping

**Comment by quliping** [comment]
> Sample names in the coverage file are generated using the forward reads when using -1 and -2 parameters, both pairs are used during mapping

Thank you for your reply. I have the other question that how to make coverM use the bam file which was generated by previous run of itself? I specified bam files with the - b parameter, but there was an error. Could you please help me to see what happend? Thanks a lot!
![image](https://github.com/wwood/CoverM/assets/39583607/0709cde3-11cb-4f42-86a9-d0871c564b5d)

**Comment by wwood** [comment]
Hi, apologies for the slow response.

1. Use the `-s '~'` flag. When mapping using a bam file cache directory, CoverM uses the `~` separator to associate contig names and genomes.
2. There's no reason you cannot calculate TPM for a genome - you just consider all contigs at once using the number of reads mapped to all contigs.
3. There's a lot of sub-questions mixed up in this one. To me it isn't clear what you are trying to assess exactly. The total abundance of your genus? The relative abundance of each species in the genus? etc. Plain old relative_abundance is probably fine for most of these questions.

**Comment by clementcoclet** [comment]
Hi Ben,

I'm currently facing some challenges while trying to utilize **coverM genome**. I have a folder containing (sorted) BAM files and another folder with genomes, which consists of multiple membership sequences per genome.

Initially, I ran the command:
`coverm genome -b LOXAHATCHEE_PROJECT/04_READ_MAPPING/*/*_sorted.bam -d LOXAHATCHEE_PROJECT/07_BINNING/07A_vRHYME_OUTPUT/vRhyme_best_bins_fasta/ -x fasta
`
However, I encountered an error similar to the one reported by another user: "**Error: There are no found reference sequences that are a part of a genome.**" Following your suggestion, I added the `-s '~'` option:
`coverm genome -b LOXAHATCHEE_PROJECT/04_READ_MAPPING/*/*_sorted.bam -d LOXAHATCHEE_PROJECT/07_BINNING/07A_vRHYME_OUTPUT/vRhyme_best_bins_fasta -x fasta -s '~'
`
Unfortunately, this led to another error, stating that `--genome-fasta-directory` cannot be used when the `-s` argument is provided. It appears that we need to use the `--reference` argument in such cases. However, using `--reference` prevents us from using the bam folder, as `--bam-files` cannot be used when the `--reference` argument is provided.

My understanding is that when using the` -s` argument, it seems we are unable to utilize existing BAM files. Could you provide any insights or recommendations on how to address this situation? 

I appreciate your assistance.
Clément

**Comment by wwood** [comment]
Coverm needs to know which contigs belong to which genomes. You are confusing it by providing the info twice, once with -s and once with genome fasta files.

You shouldn't need to specify -r with -s. Just -b and -s should do it.

Hth

-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT
________________________________
