### ISSUE TITLE
pay attention to skani accuracy below 85% ANI

### ISSUE THREAD

**Issue by jianshu93** [wwood/CoverM#199]
Dear CoverM team,

I remember I suggested skani some time ago, and glad to see you included it in the newest version. However, you might notice inaccuracy estimations below 85% ANI. While with the newest version of fastANI, it is almost as accurate as blastn-based ANI. See my blog here: https://jianshu93.github.io/blog/ANI-calculator/

I would suggest only shift to skani for above 90% ANI while using fastANI for below 90% clustering threshold by default, but not allow users to choose fastANI or skani, for example, if I want to dereplicate at 85% ANI to choose genus level representatives, clearly fastANI is a better option than skani. Does it make sense? And if there is a paper on CoverM in preparation, I would be happy to contribute and provide those benchmark results that I have been studying.

Jianshu

**Comment by wwood** [comment]
Thanks @jianshu93 - Galah (which CoverM uses for derep). I suppose you would also suggest requiring FastANI 1.34 and using the -correct flag?

@AroneyS it seems the docs are wrong - https://wwood.github.io/CoverM/coverm-genome.html#dereplication-genome-clustering still talks about FastANI - can you make sure skani is being used by default and the docs reflect this please?

**Comment by jianshu93** [comment]
Hello @wwood,

Yes I would suggest so since the corrected flag is more close to the actual alignment-based ANI. We will update the bioconda channel for the newest --correct option soon.


Jianshu

**Comment by jianshu93** [comment]
hello @wwood  pre-clustering default is now skani, which is very dangerous because below 82% ANI skani output is 0. I would suggest use finch version of minhash (essential the same with Mash without over-sketching) , above 90% ANI, skani is as good as fastANI, so I think it is ok to use. 

Thanks,

Jianshu

**Comment by jianshu93** [comment]
Hi Team, 

GSearch is out! It can search GTDB or entire Refseq/IMG_VR in almost no time! and the running time does not grow with increasing number of genomes! https://academic.oup.com/nar/advance-article/doi/10.1093/nar/gkae609/7714450

I believe it will solve all the problems all other search and classification tools are having!

Thanks,

Jianshu

**Comment by wwood** [comment]
Hi @jianshu93 

Almost the end of the year, and we still haven't responded to this.

Thank you for the obsevation about low ANI - @AroneyS is implementing a check for this so that low ANIs generate an error. 

For gsearch, we might go down that path in future, though it does seem to fit exactly within the usual dereplication framework. If we start to integrate those kinds of things, we might see feature creep where CoverM effectively tries to do all community profiling modalities, which would be a lot of maintenance work.

Happy holidays.
