### ISSUE TITLE
Error: fastANI executable not found despite being installed

### ISSUE THREAD

**Issue by x1zh0u** [wwood/CoverM#204]
Hi,

I'm encountering a dependency problem while running coverm. It seems like everything is set up properly, but coverm is having trouble locating the fastANI executable, even though it's accessible.

Steps to Reproduce:

Execute the following command:
`nohup sh -c 'cat datalist | while read line
do
time coverm genome --coupled ../zhou202306/temp/bin_data/${line}_paired_1.fastq ../zhou202306/temp/bin_data/${line}_paired_2.fastq -d 10_bin/${line}_rf/metawrap_50_10_bins -x fa -t 120 -m relative_abundance -m rpkm -m mean --dereplicate --dereplication-ani 95 > 10_bin/coverm/${line}.output.tsv 
done' >> coverm.out 2>&1 &`

An error occurs stating that the fastANI executable cannot be found, despite being installed and accessible in the environment.

Additional Information:
Output of `which fastANI`: /nfs/sopt/miniconda3/envs/coverm/bin/fastANI

Error Message:
[2024-03-05T15:42:30Z ERROR bird_tool_utils::external_command_checker] Could not find an available fastANI executable.
[2024-03-05T15:42:30Z ERROR bird_tool_utils::external_command_checker] The STDERR was: ""
[2024-03-05T15:42:30Z ERROR bird_tool_utils::external_command_checker] Cannot continue without fastANI. Finding version of `fastANI --version 2>&1` failed

Notes:
I have confirmed that the fastANI executable is installed in the specified environment, and running which fastANI returns the correct path to the executable.

Thank you for your assistance in resolving this issue.

**Comment by wwood** [comment]
Hi,

This seems a bit strange to me. I wonder if the issue is that you are running it from within another call to `sh` ? What happens when you run one of the for loop directly?

**Comment by x1zh0u** [comment]
Hi,

When I run one of the for loops directly, it works without any issues and completes successfully!

Thanks.

Xi Zhou

**Comment by x1zh0u** [comment]
Hi,

When I run one of the for loops directly, it works without any issues and completes successfully!

Thanks.

Xi Zhou
