### ISSUE TITLE
Mean coverage calculation

### ISSUE THREAD

**Issue by ramiroricardo** [wwood/CoverM#209]
Dear all,

Thanks for a great tool. I have a basic question, regarding the mean coverage calculation. In the example, the following is stated:

"The two reads have 10 and 9 bases aligned exactly, averaged over 1000-2*75 bp (length of contig minus 75bp from each end)."

What is the reason for removing 75bp from each end of the contig?

Best,

Ricardo Ramiro

**Comment by wwood** [comment]
Hi,

The idea is to avoid there being coverage artefacts. At the ends of contigs it is harder to map reads - at the extreme case of a read only mapping to the last base pair of a contig, it won't be mapped, so the coverage will be artificially reduced.

There may also be repeats at the ends of contigs, which would inappropriately inflate coverage.

This idea was taken from the metabat coverage calculation script, called `jgi_..` - sorry I forget the exact name.
HTH, ben

**Comment by ramiroricardo** [comment]
Great, thanks for your quick reply.
