### ISSUE TITLE
cryptic error when running coverM genome 

### ISSUE THREAD

**Issue by nixon444** [wwood/CoverM#216]
Hi,

I've been trying to run coverM on a number of genome sets to calculate relative abundance, but I get this same error each time:

thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/coverage_printer.rs:467:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

The command I used is:

coverm genome -1 coverM/108_1.fastq -2 coverM/108_2.fastq -d goodbins/ -x fa -t 16 -v -o 108_binabund_output.tsv

What does this mean, and what am I doing wrong here?

For info, I am running this in a container which has worked for others in my group, on our group server

Cheers,
Sophie

**Comment by CHEN15623** [comment]
I have the same problem. Have you solved it？

**Comment by CHEN15623** [comment]
> Hi,
> 
> I've been trying to run coverM on a number of genome sets to calculate relative abundance, but I get this same error each time:
> 
> thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/coverage_printer.rs:467:35 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> The command I used is:
> 
> coverm genome -1 coverM/108_1.fastq -2 coverM/108_2.fastq -d goodbins/ -x fa -t 16 -v -o 108_binabund_output.tsv
> 
> What does this mean, and what am I doing wrong here?
> 
> For info, I am running this in a container which has worked for others in my group, on our group server
> 
> Cheers, Sophie

I have the same problem. Have you solved it？

**Comment by CHEN15623** [comment]
> Hi,
> 
> This is a strange one. Can you send the bins and reads to me e.g. via Dropbox? Thanks

Thanks, my problem has been solved, which is probably caused by a mismatch between the version of samtools and htslib

Best
Chen
