### ISSUE TITLE
How can I use CoverM to calculate the abundace of hybrid-assembly recovered MAGs?

### ISSUE THREAD

**Issue by brilliant2643** [wwood/CoverM#217]
Hi!
I'm planning to calculate the abundance of MAGs, but I don't know whether the assembly method will affect the command and input data of CoverM. By the way, I use nanopore reads and Illumina reads to assemble the configs, and recovered MAGs from those contigs.
Do you have any idea about what command and input data I should use to run CoverM?

Thanks a lot and looking forward to your reply!
Sushi

**Comment by wwood** [comment]
Hi,

Apologies for the slow response.

CoverM doesn't really mind what the contigs/MAGs are generated from. The more important thing is to use the correct value for `-p` / `--mapper` for the type of reads you have. See https://wwood.github.io/CoverM/coverm-genome.html for more details on this.

HTH, ben

**Comment by brilliant2643** [comment]
> Hi,
> 
> Apologies for the slow response.
> 
> CoverM doesn't really mind what the contigs/MAGs are generated from. The more important thing is to use the correct value for `-p` / `--mapper` for the type of reads you have. See https://wwood.github.io/CoverM/coverm-genome.html for more details on this.
> 
> HTH, ben

Hi,
Thanks for your reply, I have used Illumina reads to calculate coverm and it works. 

Sushi
