### ISSUE TITLE
compressed fasta input

### ISSUE THREAD

**Issue by jvollme** [wwood/CoverM#218]
The Docs specify that for fastq input files, gzip compressed files are accepted, but nothing is specified for the input reference fastas.
Does this mean coverm currently only accepts uncompressed fastas?

If that is the case, would you consider adding support for compressed fastas or for piping the reference-input from stdin? I try to avoid storing sequence data in uncompressed form, and extracting them to disk temporarily just to delete them again when the tool is finished is a bit of a hassle (and a bottleneck since the additional read/write operations take longer).

**Comment by jvollme** [comment]
ok forget i asked. i just tested it and it can read compressed fastas. But maybe this would be worth mentioning explicitely in the help function and docs? Because unfortunately quite often tools are actually not capable of handling compressed fastas...

**Comment by wwood** [comment]
Good point - applied. Thanks.
