### ISSUE TITLE
[Suggestion] Add TPM as a method for calculating coverage

### ISSUE THREAD

**Issue by apcamargo** [wwood/CoverM#22]
Currently, CoverM offers the user to output contig and genome coverage in RPKM. This metric is cool because it corrects for both library size and contig/genome length.

TPM (transcripts per million) is another metric with the same positive aspects and has the advantage that the sum of all contigs/genomes must add to 1.000.000. More on this [here](https://haroldpimentel.wordpress.com/2014/05/08/what-the-fpkm-a-review-rna-seq-expression-units/). Nowadays, most RNA-Seq quantification software use TPM instead of RPKM.

A the advantage of TPM becomes clear when comparing the coverage between two libraries. If a contig/genome has a higher TPM in library A than in library B, you can infer that this contig/genome is more abundant in library A. If you observed the same with RPKM values, you wouldn't be able to reach the same conclusion, as the total RPKM varies between different libraries.

**Comment by wwood** [comment]
I got there in the end.. thanks for the suggestion and useful link.

**Comment by apcamargo** [comment]
That's awesome! Thanks, Ben
