### ISSUE TITLE
Discussion/request: Read extraction for multiple references

### ISSUE THREAD

**Issue by strejcem** [wwood/CoverM#220]
Hi,

I’m looking for a tool that can extract FASTQ reads mapped to multiple individual references, but specifically for long nanopore reads. Unfortunately, I haven’t been able to find any tool that supports long reads in this context. Essentially, I’m seeking functionality similar to BBsplit.sh, but compatible with long reads.

Would it be possible to extend coverm to support this?

Thank you!
Michal

EDIT: Sorry for messing up the title and closing/opening

**Comment by wwood** [comment]
Hi @strejcem thanks for the thought, but I think this functionality is a bit far outside the current structure of CoverM at the moment. Perhaps in the future.
