### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by XRL-1343959526** [wwood/CoverM#223]
![image](https://github.com/u![1727238875251](https://github.com/user-attachments/assets/7f96f165-fca8-4256-8195-6aacc99f5da6)ttachments/assets/518c055a-020f-4f10-9ee5-72a509e46e5f)

**Comment by wwood** [comment]
Hi,

It seems your images aren't showing up, so I can't help. I've closed your discussion in favour of this issue.
ben
