### ISSUE TITLE
the difference between "--min-read-aligned-percent" and "--min-read-aligned-percent-pair"

### ISSUE THREAD

**Issue by HAIS-st** [wwood/CoverM#233]
hi，I would like to know what is the difference between "--min-read-aligned-percent" and "--min-read-aligned-percent-pair" in the filter and why the results are inconsistent
thanks

**Comment by wwood** [comment]
Hi,

The first relates to each read, the second is calculated across the pair.

In the first, one side of a pair of reads can be filtered out, whereas in the second sets of pairs are filtered out.

**Comment by HAIS-st** [comment]
> 你好
> 
> 第一个与每个读取相关，第二个是跨对计算的。
> 
> 在第一组中，可以过滤掉一对 reads 的一侧，而在第二组 pairs 中被过滤掉。

thanks，Which filtering method is more appropriate when calculating the abundance of contigs in a metagenome?

**Comment by wwood** [comment]
I would probably use the first one, because the ends of the contigs can mess with the pairing.

**Comment by HAIS-st** [comment]
> I would probably use the first one, because the ends of the contigs can mess with the pairing.

thanks
