### ISSUE TITLE
a question about building 

### ISSUE THREAD

**Issue by Andy320** [wwood/CoverM#29]
@wwood 
I notice that an issue opended by you as follows:
https://github.com/rust-bio/rust-htslib/issues/80

I came across a similiar issue :
https://github.com/rust-rocksdb/rust-rocksdb/issues/418

 The same error was produced, although in diffrent projects.
"undefined reference to symbol '__printf_chk@@GLIBC_2.3.4'"

so I want to know 
what is the root cause ?
how did you get rid of it?

thanks a lot

**Comment by wwood** [comment]
Hi,

Can I ask how you are compiling it, and which library is causing the problem? The htslib rust issue has been solved by changing the rust-htslib source code here: https://github.com/rust-bio/rust-htslib/pull/111

**Comment by Andy320** [comment]
@wwood 
The lib is rocksdb-sys. It seems that htslib does not support musl libs before which cause your problem. I am not sure about that in rocksdb. I will try the compiling using target  x86_64-unknown-linux-gnu

**Comment by Andy320** [comment]
close this issue.
