### ISSUE TITLE
Add support for URMAP

### ISSUE THREAD

**Issue by jianshu93** [wwood/CoverM#32]
A very fast mapping tool URMAP(https://drive5.com/urmap/) can advance mapping processes and thus calculation of coverage for large metagenomic datasets. I would say the is a very good one for enhancing the CoverM in terms of speed when a large dataset is analysized.

**Comment by wwood** [comment]
I'm interested and mostly implemented this, but then I ran into https://github.com/rcedgar/urmap/issues/5 which means URMAP support is effectively a no-go at this time, I'm afraid.

**Comment by wwood** [comment]
I'm closing this issue for now since it cannot be fixed unless URMAP changes. Happy to re-open if there are changes.
