### ISSUE TITLE
ERROR coverm::bam_generator

### ISSUE THREAD

**Issue by DDavila10** [wwood/CoverM#38]
Hi, 

I am currently using coverm and I have the following error. I am using a conda environment.
Could you please help me to solve this problem?

Thanks a lot!

coverm genome --threads 24 \
--genome-fasta-directory dereplicated_genomes \
--genome-fasta-extension fa \
--coupled \
${SampleName}_1.fastq.gz \
${SampleName}_2.fastq.gz \
> abundances-${SampleName}.txt

[2020-09-10T08:54:37Z INFO  coverm] Using min-covered-fraction 10%
[2020-09-10T08:54:37Z INFO  coverm::external_command_checker] Found minimap2 version 2.17-r941 
[2020-09-10T08:54:37Z INFO  coverm::external_command_checker] Found samtools version 1.9 
[2020-09-10T08:54:37Z INFO  coverm] Generating concatenated reference FASTA file of 1296 genomes ..
[2020-09-10T08:54:47Z INFO  coverm] Not pre-generating minimap2 index
[2020-09-10T09:04:53Z ERROR coverm::bam_generator] Failed to correctly find or parse BAM file at "/tmp/coverm_fifo.rgGGpR3gjykp/foo.pipe": unable to open SAM/BAM/CRAM file at /tmp/coverm_fifo.rgGGpR3gjykp/foo.pipe
[2020-09-10T09:04:53Z ERROR coverm::bam_generator] Error when running mapping process: ["bash -c \"set -e -o pipefail; minimap2 --split-prefix /tmp/.tmpnhiasQ -a -x sr  -t 24  \'/tmp/.tmpzO3nxq\' \'ERR3357550_1.fastq.gz\' \'ERR3357550_2.fastq.gz\' 2>/tmp/.tmpnEy3yu  | remove_minimap2_duplicated_headers| samtools sort -T \'/tmp/coverm_fifo.rgGGpR3gjykp/coverm-make-samtools-sortcHted5\' -l0 -@ 23 2>/tmp/.tmpofcBac > \"/tmp/coverm_fifo.rgGGpR3gjykp/foo.pipe\"\""]
[2020-09-10T09:04:53Z ERROR coverm::bam_generator] The STDERR for the MINIMAP2_SR part was: [M::mm_idx_gen::82.366*1.79] collected minimizers
    [M::mm_idx_gen::89.285*3.09] sorted minimizers
    [M::main::89.361*3.09] loaded/built the index for 281394 target sequence(s)
    [M::mm_mapopt_update::89.361*3.09] mid_occ = 1000
    [M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 281394
    [M::mm_idx_stat::101.601*2.83] distinct minimizers: 498419246 (91.88% are singletons); average occurrences: 1.123; average spacing: 6.010
    [M::worker_pipeline::107.834*3.36] mapped 505514 sequences
    [M::worker_pipeline::109.677*3.59] mapped 505606 sequences
    [M::worker_pipeline::111.570*3.83] mapped 505222 sequences
    [M::worker_pipeline::113.712*4.17] mapped 504902 sequences
    [M::worker_pipeline::115.087*4.32] mapped 505222 sequences
    [M::worker_pipeline::116.950*4.59] mapped 505260 sequences
    [M::worker_pipeline::118.572*4.76] mapped 505188 sequences
    [M::worker_pipeline::120.220*4.96] mapped 505270 sequences
    [M::worker_pipeline::121.925*5.18] mapped 505106 sequences
    [M::worker_pipeline::123.434*5.32] mapped 505280 sequences
    [M::worker_pipeline::125.082*5.48] mapped 505712 sequences
    [M::worker_pipeline::127.186*5.72] mapped 505718 sequences
    [M::worker_pipeline::128.916*5.90] mapped 505724 sequences
    [M::worker_pipeline::130.532*6.07] mapped 505458 sequences
    [M::worker_pipeline::132.568*6.29] mapped 506024 sequences
    [M::worker_pipeline::134.254*6.46] mapped 505836 sequences
    [M::worker_pipeline::135.796*6.61] mapped 506122 sequences
    [M::worker_pipeline::137.256*6.70] mapped 505978 sequences
    [M::worker_pipeline::138.843*6.85] mapped 506408 sequences
    [M::worker_pipeline::140.377*6.95] mapped 506108 sequences
    [M::worker_pipeline::142.162*7.11] mapped 507162 sequences
    [M::worker_pipeline::144.127*7.28] mapped 506566 sequences
    [M::worker_pipeline::145.615*7.37] mapped 506030 sequences
    [M::worker_pipeline::147.643*7.54] mapped 506836 sequences
    [M::worker_pipeline::149.444*7.68] mapped 506404 sequences
    [M::worker_pipeline::151.177*7.83] mapped 506370 sequences
    [M::worker_pipeline::152.508*7.93] mapped 507040 sequences
    [M::worker_pipeline::153.892*8.03] mapped 507056 sequences
    [M::worker_pipeline::155.366*8.10] mapped 507014 sequences
    [M::worker_pipeline::157.321*8.25] mapped 506124 sequences
[M::worker_pipeline::159.178*8.39] mapped 505852 sequences
    [M::worker_pipeline::161.052*8.54] mapped 505382 sequences
    [M::worker_pipeline::162.381*8.62] mapped 505752 sequences
    [M::worker_pipeline::163.996*8.72] mapped 505552 sequences
    [M::worker_pipeline::165.873*8.86] mapped 505936 sequences
    [M::worker_pipeline::167.137*8.94] mapped 505660 sequences
    [M::worker_pipeline::168.783*9.05] mapped 505660 sequences
    [M::worker_pipeline::170.088*9.12] mapped 505862 sequences
    [M::worker_pipeline::171.830*9.23] mapped 505972 sequences
    [M::worker_pipeline::173.415*9.32] mapped 505870 sequences
    [M::worker_pipeline::175.267*9.44] mapped 506196 sequences
    [M::worker_pipeline::176.666*9.51] mapped 505790 sequences
    [M::worker_pipeline::178.487*9.60] mapped 506158 sequences
    [M::worker_pipeline::180.210*9.68] mapped 506236 sequences
    [M::worker_pipeline::181.995*9.79] mapped 506478 sequences
    [M::worker_pipeline::183.550*9.86] mapped 506164 sequences
    [M::worker_pipeline::185.111*9.91] mapped 506524 sequences
    [M::worker_pipeline::187.197*10.02] mapped 506418 sequences
    [M::worker_pipeline::189.316*10.13] mapped 507062 sequences
    [M::worker_pipeline::192.166*10.21] mapped 506520 sequences
    [M::worker_pipeline::197.958*10.42] mapped 508062 sequences
    [M::worker_pipeline::200.087*10.47] mapped 506748 sequences
    [M::worker_pipeline::202.457*10.57] mapped 506850 sequences
    [M::worker_pipeline::204.451*10.63] mapped 506448 sequences
    [M::worker_pipeline::206.684*10.72] mapped 507308 sequences
    [M::worker_pipeline::208.960*10.79] mapped 506604 sequences
    [M::worker_pipeline::211.129*10.87] mapped 506274 sequences
    [M::worker_pipeline::213.588*10.97] mapped 505386 sequences
    [M::worker_pipeline::216.396*11.07] mapped 504562 sequences
    [M::worker_pipeline::218.540*11.12] mapped 505062 sequences
    [M::worker_pipeline::222.208*11.15] mapped 505106 sequences
    [M::worker_pipeline::224.930*11.21] mapped 505056 sequen
[2020-09-10T09:04:53Z ERROR coverm::bam_generator] The STDERR for the samtools sort part was: 
[2020-09-10T09:04:53Z ERROR coverm::bam_generator] Cannot continue since mapping failed.

**Comment by wwood** [comment]
Hi,

Thanks for your interest. Just to be clear, this is what you ran? With `SampleName` = `ERR3357550`

```
coverm genome --threads 24 \
--genome-fasta-directory dereplicated_genomes \
--genome-fasta-extension fa \
--coupled \
${SampleName}_1.fastq.gz \
${SampleName}_2.fastq.gz \
> abundances-${SampleName}.txt
```

Given that, what version of CoverM are you running? Usually the first line of the log has this but it seems to be missing.

My only thought as to a cause is that maybe the entire process was killed when e.g. the mapping took too much CPU or RAM?

ben

**Comment by DDavila10** [comment]
Hi Ben,

Thanks a lot for your reply and valuable help!
Yes, I am running that with the sample name ERR3357550. I used the lattes version and the version 0.3.2. and still have the same problem. I am following the tutorial of the iMGMC (https://github.com/tillrobin/iMGMC/blob/master/tutorials/map-to-MAGs-Krona-plot.md). I created the conda environment using a yaml file. 

What do you suggest that I can do to realized if was the CPU or RAM?

and again, thanks a lot for the help.

Daniel

**Comment by wwood** [comment]
Hmm, do you mean exactly following the tutorial, with the same MAGs?

**Comment by DDavila10** [comment]
Yes, I want to checked that everything is working before using my sequencing data

**Comment by wwood** [comment]
Usually if a process is killed due to running out of RAM it fails it will say "Killed" somewhere on the commandline (but not necessarily by coverm's caching of STDERR I don't think). Too much CPU is usually only a problem when you've run coverm via a queuing system and haven't given enough walltime when submitting the job. Either of those true?

**Comment by wwood** [comment]
Hi again,

I've managed to reproduce something like this, under a RAM-limited condition. If you force a small minimap2 multipart index, then you can reduce its memory consumption at the expense of extra CPU cycles. Does this work?

```
coverm genome --threads 24 --genome-fasta-directory dereplicated_genomes  --genome-fasta-extension fa  --coupled ERR3357550_1.fastq.gz ERR3357550_2.fastq.gz --minimap2-parameters "-I 500M"
```

**Comment by wwood** [comment]
Oh and when running your code on the coverm 0.5.0 I found a different error was getting in the way:

```The contig '{}' has been assigned to multiple genomes, \
                        at least '{}' and '{}'. You may try not using \
                        --reference and let coverm generate a reference of \
                        concatenated contigs, or rename the contigs in your \
                        genome file(s).
```
I've fixed that error now (and added tests so it doesn't re-appear), so you'll want to test using the development master branch version. I believe just running 0.3.2 should work with that `-I` as above, but I suggest updating if possible.

**Comment by DDavila10** [comment]
Hi again,

Thanks a lot for the reply and valuable help, let me try your suggestion and I will let you know what happend.

**Comment by DDavila10** [comment]
Hi again,

Unfortunately, reduce the memory consumption does not work and generate another error. 

[2020-09-15T09:22:32Z INFO  coverm] CoverM version 0.3.2
[2020-09-15T09:22:32Z INFO  coverm] Using min-covered-fraction 10%
[2020-09-15T09:22:32Z INFO  coverm::external_command_checker] Found minimap2 version 2.17-r941 
[2020-09-15T09:22:35Z INFO  coverm::external_command_checker] Found samtools version 1.9 
[2020-09-15T09:22:35Z INFO  coverm] Generating concatenated reference FASTA file of 1296 genomes ..
[2020-09-15T09:24:47Z INFO  coverm] Not pre-generating minimap2 index
[2020-09-15T09:33:53Z WARN  coverm::genome] No primary alignments were observed for sample ERR3357550_1.fastq.gz - perhaps something went wrong in the mapping?
[2020-09-15T09:33:53Z INFO  coverm::genome] In sample 'ERR3357550_1.fastq.gz', found 0 reads mapped out of 0 total (NaN%)
[2020-09-15T09:33:53Z ERROR coverm::bam_generator] Error when running mapping process: ["bash -c \"set -e -o pipefail; minimap2 --split-prefix /tmp/.tmpJRsrW2 -a -x sr -I 500M -t 24  \'/tmp/.tmpcaYDbr\' \'ERR3357550_1.fastq.gz\' \'ERR3357550_2.fastq.gz\' 2>/tmp/.tmpv3HoZ3  | remove_minimap2_duplicated_headers| samtools sort -T \'/tmp/coverm_fifo.DuW6I3SJoaqg/coverm-make-samtools-sortNFlE10\' -l0 -@ 23 2>/tmp/.tmpQuxFMg > \"/tmp/coverm_fifo.DuW6I3SJoaqg/foo.pipe\"\""]
[2020-09-15T09:33:53Z ERROR coverm::bam_generator] The STDERR for the MINIMAP2_SR part was: [M::mm_idx_gen::11.986*1.83] collected minimizers
    [M::mm_idx_gen::13.250*2.79] sorted minimizers
    [M::main::13.250*2.79] loaded/built the index for 43934 target sequence(s)
    [M::mm_mapopt_update::13.250*2.79] mid_occ = 1000
    [M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 43934
    [M::mm_idx_stat::14.107*2.68] distinct minimizers: 80951768 (97.78% are singletons); average occurrences: 1.028; average spacing: 6.010
    [M::worker_pipeline::16.701*3.11] mapped 505514 sequences
    [M::worker_pipeline::18.423*3.53] mapped 505606 sequences
    [M::worker_pipeline::19.832*3.85] mapped 505222 sequences 
[M::worker_pipeline::259.963*7.74] mapped 507900 sequences
    [M::worker_pipeline::261.404*7.74] mapped 507854 sequences
    [M::worker_pipeline::262.755*7.74] mapped 508576 sequences
    [M::worker_pipeline::264.211*7.74] mapped 507980 sequences
    [M::worker_pipeline::265.574*7.74] mapped 508318 sequences
    [M::worker_pipeline::267.039*7.74] mapped 508200 sequences
    [M::worker_pipeline::267.560*7.75] mapped 257564 sequences
    [M::mm_idx_gen::280.588*7.47] collected minimizers
    [M::mm_idx_gen::281.524*7.52] sorted minimizers
    [M::main::281.524*7.52] loaded/built the index for 38270 target sequence(s)
    [M::mm_mapopt_update::281.524*7.52] mid_occ = 1000
    [M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 38270
    [M::mm_idx_stat::282.455*7.50] distinct minimizers: 80120313 (96.96% are singletons); average occurrences: 1.039; average spacing: 6.008
    [M::worker_pipeline::284.526*7.49] mapped 505514 sequences
    [M::worker_pipeline::285.924*7.50] mapped 505606 sequences
    [M::worker_pipeline::287.279*7.50] mapped 505222 sequences
    [M::worker_pipeline::288.813*7.52] mapped 504902 sequences
    [M::worker_pipeline::290.366*7.53] mapped 505222 sequences
[M::worker_pipeline::401.083*8.02] mapped 507840 sequences
    [M::worker_pipeline::402.414*8.03] mapped 508146 sequences
    [M::worker_pipeline::403.708*8.03] mapped 506988 sequences
    [M::worker_pipel
[2020-09-15T09:33:53Z ERROR coverm::bam_generator] The STDERR for the samtools sort part was: 
[2020-09-15T09:33:53Z ERROR coverm::bam_generator] Cannot continue since mapping failed.

**Comment by DDavila10** [comment]
This is the bash script that I am using


```
#!/bin/sh
#SBATCH -p blade
#SBATCH -n 1
#SBATCH -c 40

coverm genome --threads 24 --genome-fasta-directory dereplicated_genomes  --genome-fasta-extension fa  \
--coupled ERR3357550_1.fastq.gz ERR3357550_2.fastq.gz --minimap2-parameters "-I 500M"
```

**Comment by wwood** [comment]
Hmm, so you have submitted that to a queue? If so what is the ram available for the job?
________________________________

**Comment by DDavila10** [comment]
yes, I applied

 #SBATCH --mem-per-cpu=600

**Comment by wwood** [comment]
Sorry I'm not familiar with the "SBATCH" notation. In total for your job, how much RAM was there?

**Comment by DDavila10** [comment]
Hi again ben,

I run sstat <jobId> --format=AveRSS,AveVMSize,MaxRSS,MaxRSSTask

AveRSS
    Average resident set size of all tasks in job.

AveVMSize
    Average Virtual Memory size of all tasks in job

MaxRSS
    Maximum resident set size of all tasks in job.

MaxRSSTask
    The task ID where the maxrss occurred.

This is the output 

    AveRSS       AveVMSize     MaxRSS      MaxRSSTask 
----------      ----------      ----------      ---------- 
  4854976K     6540740K     5010668K           0 

If I understood correctly, the SSR is the portion of memory occupied by a process that is held in the main memory (RAM). Is this answer to your question?

**Comment by wwood** [comment]
Seems like then that's a problem with the RAM then - the original page says you'll need 32G, and seems like you only have about 6 there.

**Comment by wwood** [comment]
Hi,

I'm probably clutching at straws here, but does it work with the updated one? If you run the attached statically compiled binary in the same environment that'll test that theory (after gunzip).

[coverm.gz](https://github.com/wwood/CoverM/files/5243601/coverm.gz)

**Comment by DDavila10** [comment]
Hi Ben,

That solves the problem. Thanks a lot!

**Comment by wwood** [comment]
Good to hear. Thanks for persevering.
________________________________

**Comment by microbial-cookie** [comment]
Hi developer, 

I meet the same problem in using Coverm, how to use the [coverm.gz](https://github.com/wwood/CoverM/files/5243601/coverm.gz) to solve, I am confused to install it in linux?? please help me, thanks!!!
