### ISSUE TITLE
change tmp path

### ISSUE THREAD

**Issue by ShangjinTan** [wwood/CoverM#41]
Some files are written to directory /tmp, where we only have a very small volume. Processes crashes easily when multiple tasks are running simutaneously. It would be the best if the path can be set explicitly via a parameter.

**Comment by wwood** [comment]
Hi,

This can be controlled by setting environment variables, e.g. `TMPDIR`. This isn't a parameter that CoverM can take directly, but can nevertheless be changed by users (and this mechanism is common to many programming languages). The specific function being used to find the temporary directory is documented here:
https://doc.rust-lang.org/std/env/fn.temp_dir.html

Does that help?
Thanks, ben

**Comment by ShangjinTan** [comment]
Yes, nice, very helpful. Thanks.

**Comment by wwood** [comment]
Documented properly now, so closing.
