### ISSUE TITLE
the rationale of genome coverage calculation

### ISSUE THREAD

**Issue by chenyj8** [wwood/CoverM#46]
Hi,

I have several MAGs and would like see their coverage across my samples. I am curious about the rationale of genome coverage calculation in CoverM. Is it the mean of contig coverage?

**Comment by wwood** [comment]
Hi,

Almost, but not quite. It is the mean of the contig coverage, but a weighted mean where each contig gets its length in weigtht. Hope that helps

**Comment by chenyj8** [comment]
> Hi,
> 
> Almost, but not quite. It is the mean of the contig coverage, but a weighted mean where each contig gets its length in weigtht. Hope that helps

Thanks. But maybe weighted is not necessary if the goal is to compare the same MAGs across different samples? Also, can I sum the genome coverage at a specific taxonomic level? For example, summing the coverage of MAGs classified as Proteobacteria?

**Comment by wwood** [comment]
>But maybe weighted is not necessary if the goal is to compare the same MAGs across different samples?

I don't follow what this has to do with contig lengths.

>Also, can I sum the genome coverage at a specific taxonomic level? For example, summing the coverage of MAGs classified as Proteobacteria?

Not from within CoverM, because CoverM does not know anything about taxonomy, at least for now.

**Comment by chenyj8** [comment]
> > But maybe weighted is not necessary if the goal is to compare the same MAGs across different samples?
> 
> I don't follow what this has to do with contig lengths.
> 
> > Also, can I sum the genome coverage at a specific taxonomic level? For example, summing the coverage of MAGs classified as Proteobacteria?
> 
> Not from within CoverM, because CoverM does not know anything about taxonomy, at least for now.

OK, thank you for your reply.
