### ISSUE TITLE
Extract unmapped reads

### ISSUE THREAD

**Issue by jsgounot** [wwood/CoverM#62]
Hi,

first thanks for your tool, it's really usefull. I used coverm to determine MAGs abundance with my samples with options `--min-read-aligned-percent 0.75 --min-read-percent-identity 0.95` and now would like to extract unmapped reads to explore what's are behind these reads. Is it possible ? 

bests,
jsgounot

**Comment by wwood** [comment]
Hi,

Thanks for your interest. I would suggest running `genome` mode with `--bam-file-cache-directory` to generate BAM files. Unfortunately, these BAM files have not been filtered for alignment thresholds. So, you would then have to run `filter` mode with the thresholding flags to unset the mappings. Then these sequences can be extracted from the BAM file with samtools.

Hope that helps.
ben

**Comment by jsgounot** [comment]
Thanks, I overlooked the documentation and didn't see the filter mode. Will try that.

**Comment by wwood** [comment]
No problem.
