### ISSUE TITLE
Set --min-covered-fraction when calculating contig coverage using 'coverm contig',

### ISSUE THREAD

**Issue by ZongzhiWu** [wwood/CoverM#70]
Hi wwood, 
If I want to screen contigs with ≥70% of their length covered by the reads when using 'coverm contig', I wonder how to set --min-covered-fraction properly?

**Comment by wwood** [comment]
Hi, you can use `--min-covered-fraction 70` or `--min-covered-fraction 0.7`, both should work (and the logging messages should be clear what the % used was. I will improve the documentation on this.
