### ISSUE TITLE
bwa-mem2 support to improve mapping speed

### ISSUE THREAD

**Issue by jianshu93** [wwood/CoverM#72]
Dear Ben,
bwa-mem algorithm was improved and a 2x speedup is achieved. See here: https://ieeexplore.ieee.org/abstract/document/8820962?casa_token=KrlJpG5fVt8AAAAA:NUlxBO2400z4M-sFMCbDn2tSXTZj_y0si_MQgNbDvPd3y223cpV-si6b8DDWCWhl-1iSI3Gh

minimap2 is still not perfect for short reads mapping (https://lh3.github.io/2018/04/02/minimap2-and-the-future-of-bwa) but for large scale dataset the speed of minimap2 really fast. actually the syntax for bwa-mem2 is exactly the same with bwa. All need to add is to also recognize bwa-mem2 in the path, together with bwa and minimap2. I have done tests with bwa-mem2 and the output file and coverage are exactly the same with bwa but 2x speedup

Thanks,

Jianshu

**Comment by wwood** [comment]
Good idea, thanks.
