### ISSUE TITLE
I am having issues installing coverM via conda and rust

### ISSUE THREAD

**Issue by lcamVz** [wwood/CoverM#77]
Hi I am trying to install coverM but an having issues. What would be a recomendation installing coverM as an environment? one of the errors I face is:
```
UnsatisfiableError: The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - coverm=0.6.1 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.31
```
How would I got in creating an environment compatible with coverM and other M suite apps that might face similar problem?

Thank you in advance.

**Comment by wwood** [comment]
Hi,

I've not come across this before, and so not sure what you are trying to do specifically. What conda command causes this?
Thanks.

**Comment by lcamVz** [comment]
Hi, 

Thank you for the reply.

I've been using `conda install -c bioconda coverm`

**Comment by wwood** [comment]
Sorry that isn't sufficient information because the outcome will depend on what your current install is. Can you reproduce using `conda create coverm ...`?

**Comment by lcamVz** [comment]
Hi this is what I get as for errors. 

`(base) microbiomelab-ndsu@DESKTOP-4LG8ES7:~$ conda install -c bioconda coverm
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                     

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libgcc-ng conflicts for:
python=3.8 -> zlib[version='>=1.2.11,<1.3.0a0'] -> libgcc-ng[version='>=7.2.0']
python=3.8 -> libgcc-ng[version='>=7.3.0|>=7.5.0']

Package libstdcxx-ng conflicts for:
python=3.8 -> libffi[version='>=3.2.1,<3.3a0'] -> libstdcxx-ng[version='>=7.2.0']
python=3.8 -> libstdcxx-ng[version='>=7.3.0']

Package openssl conflicts for:
python=3.8 -> openssl[version='>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a']
coverm -> samtools[version='>=1.9'] -> openssl[version='>=1.0.2p,<1.0.3a|>=1.0.2r,<1.0.3a|>=1.1.1a,<1.1.2a']

Package ncurses conflicts for:
python=3.8 -> ncurses[version='>=6.1,<7.0a0|>=6.2,<7.0a0']
python=3.8 -> readline[version='>=7.0,<8.0a0'] -> ncurses[version='6.0.*|>=6.0,<7.0a0']The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - coverm -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - python=3.8 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.31`

I will try the conda create and see.

**Comment by lcamVz** [comment]
This is what I get with create:


```
(base) microbiomelab-ndsu@DESKTOP-4LG8ES7:~$ conda create -c bioconda --name coverm coverm
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                     

UnsatisfiableError: The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - coverm -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.31
```

**Comment by wwood** [comment]
Hi,

That's strange. I cannot reproduce - I suspect something is amiss with your base conda install I'm afraid.

**Comment by lcamVz** [comment]
What conda version are you running?

**Comment by wwood** [comment]
4.9.2 or a newer one on a different computer too I think.
