### ISSUE TITLE
Error when running coverM (genome mode): thread 'main' panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by zehanna** [wwood/CoverM#78]
Hello,

I've encountered an error when trying to run coverM and I was wondering if you could help.
I have installed coverM using conda like this: 

conda install -c bioconda coverm

Now I'm trying to run it in genome mode with this command:

coverm genome --bam-files . --genome-fasta-directory bins --genome-fasta-extension fa -o coverm_output

And I'm getting this error:

[2021-07-21T13:03:07Z INFO  coverm] CoverM version 0.6.1
[2021-07-21T13:03:07Z INFO  coverm] Writing output to file: coverm_output
[2021-07-21T13:03:07Z INFO  coverm] Using min-covered-fraction 10%
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/bam_generator.rs:280:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Would you have any idea what's the problem?

Thanks a lot in advance,

Hanna

**Comment by wwood** [comment]
Hi,

I suspect this might be because you are specifying a directory (`.`) for `--bam-files` when it is expecting paths to one or more files. Dees that help?

**Comment by zehanna** [comment]
Thanks, indicating the bam files specifically worked (I thought it was enough to indicate the directory they're in).
Best,
Hanna
