### ISSUE TITLE
compare genome across samples

### ISSUE THREAD

**Issue by chenyj8** [wwood/CoverM#79]
Hi

I calculate the genome rpkm within each of my samples, can I directly compare the genome rpkm across samples? Are library size and genome length taken into account in the genome mode of CoverM?

**Comment by wwood** [comment]
Hi,

Yes RPKM does take into consideration genome size and library size, as per its definition. Does that answer your question?

**Comment by chenyj8** [comment]
Thanks for your reply. 

I understand that rpkm can be calculated in the contig mode. How does CoverM calculate the rpkm in the genome mode? Sum, average, or weighted average of the rpkm of the contigs?

**Comment by wwood** [comment]
Hi,

The length of the entire genome is used in the denominator - there is no averaging across contigs unless your definition of that is equivalent.
