### ISSUE TITLE
Installation instructions unusable for HPC clusters

### ISSUE THREAD

**Issue by samfux84** [wwood/CoverM#85]
Hi,

Conda is nice to install software on a single computer/laptop, but for HPC clusters, conda is not suitable at all.

Can you please just provide a complete list with the required dependencies for CoverM? Apparently the provided list in the README is incomplete, because you talk about Rust, but Rust is not mentioned in the list of dependencies. It is also not clear what dependencies are taken from the bioconda conda channel.

I see more and more that developers are just referencing some conda channels without providing a list of the required dependencies. As developers you should know what your software depends on, so there is no need to hide this from people that would like to install the software (and who need to make sure that all required dependencies are there before installing the software). It is also not an either/or decision. You could provide the list of dependencies next to referring to a conda channel.

Best regards

Sam

**Comment by wwood** [comment]
Do these sections not answer your question?

https://github.com/wwood/CoverM#pre-compiled-binary
https://github.com/wwood/CoverM#compiling-from-source
https://github.com/wwood/CoverM#dependencies

I have put significant effort into making coverm easy to install and use - so if you have further suggestions let me know.

**Comment by samfux84** [comment]
Hi,

I am sorry for ranting about the installation instructions. There was a misunderstanding on my side. I mistakenly thought that there would by some python dependencies required as well for the installation of CoverM, which come from the bioconda conda channel. So the problem was only on my side.

> I have put significant effort into making coverm easy to install and use - so if you have further suggestions let me know.

Thank you for putting effort into making the installation easier. As a person installing hundreds of software packages on an HPC cluster I really appreciate if developers take time to document the installation well

It would be nice if you could add rust to the list of dependencies. Apart from this the installation instructions are well done.
