### ISSUE TITLE
The version of coverm

### ISSUE THREAD

**Issue by dangchenyuan** [wwood/CoverM#88]
I installed the coverm using the bioconda with the code of "conda install coverm". After success, I find the version is "CoverM version 0.3.2", not the newest 0.6.2? How can I install the newest version?

**Comment by wwood** [comment]
`conda install coverm=0.6.1` ought to do it. 0.6.2 isn't released, just 0.6.1.

Or just create a new conda environment.

**Comment by dangchenyuan** [comment]
@wwood thank you for your reply.
